### ISSUE TITLE
CLUB VERSiON 2 link fails with error "Unable to load image 'socket.127.0.0.1:12345': Unknown error (generic:107)

### ISSUE THREAD

**Issue by oxyacetylene** [987123879113/mame#13]
### MAME version

0.267

### System information

Windows 10 22H2
Ryzen 9 5900X
RTX3090
32GB RAM
en-US

### INI configuration details

```INI
it's a fresh install
```

### Emulated system/software

System 573 ddr2mc2

### Incorrect behaviour

The games don't link;
network check for DDR:
![image](https://github.com/user-attachments/assets/28d474f7-493b-4a4f-8aa4-fac03fabd20d)
network check for IIDX:
![image](https://github.com/user-attachments/assets/1f0afe1a-9f90-4b45-b1b3-0ce250ceda0f)
the DDR game flicks between seemingly random numbers under receive status sometimes
full screenshot including machine config:
![image](https://github.com/user-attachments/assets/eb37a3df-f4f7-4d7b-814f-45fc7de7c9cd)

### Expected behaviour

the games should link

### Steps to reproduce

i used command from the wiki `mame.exe ddr2mc2 -rs232_network null_modem -bitbanger1 socket.127.0.0.1:12345 -w` to start the game 

### Additional details

i also tried toggling the "Network?" to see if it would do anything and it didn't

**Comment by 987123879113** [comment]
It might be a timing issue. If you wait too long then the server from the first MAME instance times out and shuts itself down so it won't listen for connections anymore. Also, if you close one MAME instance you need to restart both to make the first MAME instance start a new server.

Close both MAME instances. Start one that will be the "server" and then press some keys to get it past the initial MAME display screens so that it's at least at the startup menu. Then immediately start the other MAME instance also connecting to "socket.127.0.0.1:12345".

**Comment by oxyacetylene** [comment]
I tried switching to a batch file to launch both instances and I'm still getting the same error. I think beatmania is fine, and it's not throwing an error, but DDR is still complaining.

The full contents of my batch file:
```
start mame.exe bmiidxc2 -rs232_network null_modem -bitbanger1 socket.127.0.0.1:12345 -w
start mame.exe ddr2mc2 -rs232_network null_modem -bitbanger1 socket.127.0.0.1:12345 -w 
```

To note: the error in the DDR log only happens in DDR, and it doesn't matter which instance is started first.

I don't mean to dodge your suggestion here, but I think timing shouldn't be an issue if I'm launching the games both directly with a batch file like this; there's only about a 1.5 second wait between both of them launching.
Also, you're talking about menus. I'm launching the games directly. Am I missing something here?
I took a video of the boot process: https://www.youtube.com/watch?v=RyZRPXyEcN8
I also didn't do the video extraction for IIDX, if that matters.

**Comment by 987123879113** [comment]
I still recommend trying to wait a few more seconds after the first MAME instance is started before you launch the second. IIDX is launching first so DDR being the one to error is what I would expect to happen. Internally MAME will try to connect to the specified socket and then when it doesn't see a server it will start listening on the specified socket port. My guess is that DDR isn't seeing the IIDX server (probably because IIDX hasn't fully finished starting the listening process yet) and then trying to listen on the same port which is no longer available.

**Comment by oxyacetylene** [comment]
So, I added a TIMEOUT to my batch file, which will automatically add a specified number of seconds timeout to my launch process. I tried 5, 7, 10, 30, and 15 seconds, with no luck. 
I also tried swapping the positions of DDR and IIDX, which should theoretically make DDR start the server and IIDX connect; this did not help, and DDR is still the one throwing the error that says "unable to load image".
I also get the error when trying to launch DDR on its own.
The current contents of my batch file:
```
START mame.exe ddr2mc2 -rs232_network null_modem -bitbanger1 socket.127.0.0.1:12345 -w 
TIMEOUT /T 15
START mame.exe bmiidxc2 -rs232_network null_modem -bitbanger1 socket.127.0.0.1:12345 -w
```
I ran DDR with the -verbose option, and this was the output:
```
hd6473644h.18e NOT FOUND (NO GOOD DUMP KNOWN) (tried in ddr2mc2 ddr2m sys573)
ge984ja.u1 ROM NEEDS REDUMP
WARNING: the machine might not run correctly.
:rs232_network:null_modem:stream: attempting to load media image socket.127.0.0.1:12345
:rs232_network:null_modem:stream: error opening image file socket.127.0.0.1:12345 with flags=00000003 (generic:107 Unknown error)
Unable to load image 'socket.127.0.0.1:12345': Unknown error (generic:107)
:rs232_network:null_modem:stream: attempting to create media image socket.127.0.0.1:12345
:rs232_network:null_modem:stream: opened image file socket.127.0.0.1:12345 with flags=00000007
```
This is opposed to the output from IIDX in verbose mode:
```
:rs232_network:null_modem:stream: attempting to load media image socket.127.0.0.1:12345
:rs232_network:null_modem:stream: opened image file socket.127.0.0.1:12345 with flags=00000003
```

**Comment by 987123879113** [comment]
You know, that actually looks like it's connecting properly. flags=00000003 is `OPEN_FLAG_WRITE | OPEN_FLAG_READ`. flags=00000007 is `OPEN_FLAG_CREATE | OPEN_FLAG_WRITE | OPEN_FLAG_READ`.

Looking at your screenshots and video again, I don't think you're running the right DDR version. The bottom right of your operator screen says JBA but Club Mix 1 and 2 are both JAA games. Club Mix 1 will have the "VER:JAA" text in red and the operator system font will be blockier, and Club Mix 2 will have "VER:JAA" text and the network check menu will say protocol version 2.0. 

Your screenshot and video has the newer less blockier font but only protocol version 1.0 with "VER:JBA" instead. It looks like to me you installed DDR 2nd Link Version (which is the same as ddr2mlb) instead of ddr2mc2. The instructions for how to install ddr2mc2 can be found [here](https://github.com/987123879113/mame/wiki/Dance-Dance-Revolution-%7C-Dancing-Stage#ddr2mc2). Please note that when it says to select "reset system", just press F3 instead to soft reset the machine since MAME has changed since I wrote the instructions and I haven't updated the wiki. I would recommend deleting `nvram/ddr2mc2` and reinstalling fresh using the wiki instructions.

**Comment by oxyacetylene** [comment]
It seems the "Press F3" part was the part I was missing. The games properly link now, but some of the settings (DDR's RX/TX baud) keep resetting themselves. 
For anyone in the future who may be googling this: the command line option -background_input enables the ability to use a controller in the unfocused window if you actually want to set up a real-life multiplayer session.
The contents of my launch batch file:
```
START mame.exe ddr2mc2 -rs232_network null_modem -bitbanger1 socket.127.0.0.1:12345 -w -verbose -screen \\.\DISPLAY2 -background_input
TIMEOUT /T 5
START mame.exe bmiidxc2 -rs232_network null_modem -bitbanger1 socket.127.0.0.1:12345 -w -verbose -screen \\.\DISPLAY3 -background_input
```
Thanks a lot, kind numbers person. I'm going to be inviting a friend over so we can enjoy this.

**Comment by 987123879113** [comment]
Glad it's working now. Have fun!

**Comment by speedymlg** [comment]
> You know, that actually looks like it's connecting properly. flags=00000003 is `OPEN_FLAG_WRITE | OPEN_FLAG_READ`. flags=00000007 is `OPEN_FLAG_CREATE | OPEN_FLAG_WRITE | OPEN_FLAG_READ`.
> 
> Looking at your screenshots and video again, I don't think you're running the right DDR version. The bottom right of your operator screen says JBA but Club Mix 1 and 2 are both JAA games. Club Mix 1 will have the "VER:JAA" text in red and the operator system font will be blockier, and Club Mix 2 will have "VER:JAA" text and the network check menu will say protocol version 2.0.
> 
> Your screenshot and video has the newer less blockier font but only protocol version 1.0 with "VER:JBA" instead. It looks like to me you installed DDR 2nd Link Version (which is the same as ddr2mlb) instead of ddr2mc2. The instructions for how to install ddr2mc2 can be found [here](https://github.com/987123879113/mame/wiki/Dance-Dance-Revolution-%7C-Dancing-Stage#ddr2mc2). Please note that when it says to select "reset system", just press F3 instead to soft reset the machine since MAME has changed since I wrote the instructions and I haven't updated the wiki. I would recommend deleting `nvram/ddr2mc2` and reinstalling fresh using the wiki instructions.

Going back to this instruction, whenever i try to either press f3 or Reset Machine after the "GE984 JAA VERSION UP COMPLETE" message pops up and after switching the CD from "install" to "runtime", it falls back to this screen once again prompting me to install the wrong version. 

<img width="1189" height="142" alt="Image" src="https://github.com/user-attachments/assets/e1f6c911-bbc0-4d39-aee4-abefa8737ddf" />
