### ISSUE TITLE
DDR Extreme Error 121?

### ISSUE THREAD

**Issue by Farthom** [987123879113/mame#4]
### MAME version

Manual build of Bemani Branch March 17 2023

### System information

Arch Linux x64

### Emulated system/software

System 573 ddrextrm

### Incorrect behaviour

Attempting to boot ddrextrm results in the system immediately displaying ERROR 121. I don't know much Japanese but the error seems to be indicating a compatibility problem with the cassette. I tried messing around with slot devices, my only options are "Game" or nothing. Switching it to nothing presents a slightly different variant of the same error. 

This worked previously on an older build, manually built from "bemani" git branch.  

### Expected behaviour

Game should boot?

**Comment by 987123879113** [comment]
My guess is you're likely using old ROMs from before the big security ROM replacement (sometime back in 0.24x range of releases). If you're seeing an error in the console about files not having matching checksums then that'd be it. Either way, this isn't an issue with the branch.

**Comment by Farthom** [comment]
Thanks a lot for the info! I didn't realize ROM files were changing on an ongoing basis. I assumed once dumped from the original game board they were effectively "permanent" and emulators would use them as is. I'm not really clear on why this is done and am willing to listen if you are willing to provide an explanation. Otherwise, you have clued me into the information I needed to get up and running. Things are working great now!!

Thanks a lot!!

**Comment by 987123879113** [comment]
The full on nerdy details: Generally ROMs don't change unless they're found to be bad or otherwise inadequate. 

A lot of the System 573 security ROM dumps were handcrafted files that were able to satisfy the game but were not technically correct. I implemented some additional security features to the security chip emulation which brought to light that the System 573 security ROMs had some bad default settings from when they were handcrafted previously so I had to remake them, this time using the game's security initialization feature to make sane default settings so the files shouldn't need to be changed again in the future.

I predict there'll probably be one more System 573 security ROM update in the (not near) future to remove the "Y" type security cartridges, which haven't been found to actually exist in the real world despite being supported by games and existing in MAME's code, but it's an entirely inconsequential problem (changing the security chip type would have no effect on the actual games) so I'm not going to be the one to make everyone update a large chunk of their System 573 ROMs again for something small like that.

Note that all of this took place in upstream MAME so it's not specific to this fork. Anyone using old security ROMs needs to update to a more recent ROM set. Don't rely on random ROM websites to have recent copies, look for full versioned ROM sets using the latest MAME version number in your search terms on archive.org or something. You may also need to wipe your NVRAM folder and reinstall the game from scratch if the error does not get resolved after updating ROMs to the known latest version (meaning, you don't see any checksum issues in the console when running the game).

Here's the actual PR where all of this changed if you're interested in the code side of things: https://github.com/mamedev/mame/pull/9137

**Comment by Farthom** [comment]
Amazing! Thanks so much for writing this out. This stuff is so fascinating!
